disabled_rules:
  # TODO: Opt in to this rule.
  - xctfail_message
opt_in_rules:
  - empty_count
  - file_header
excluded:
  - Base58String/
  - Carthage/
  - Pods/
  # TODO: Don't exclude tests
  - Tests/

identifier_name:
  min_length: 1
file_header:
  required_pattern: Copyright Keefer Taylor, 201(8|9)